import { 
  Tenant, 
  TenantSettings, 
  SiteContent, 
  Category, 
  Occasion, 
  Product, 
  Addon, 
  DeliveryZone, 
  DeliveryShift, 
  OrderLog,
  OrderStatus
} from '../types/admin';

// ==============================================================================
// DADOS INICIAIS DE EXEMPLO (SEED DATA)
// ==============================================================================

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    slug: 'elan-atelier',
    name: 'Élan Atelier Botânico',
    document: '42.189.301/0001-90',
    is_active: true,
    created_at: '2025-01-10T10:00:00Z',
  },
  {
    id: 'b1ffcd88-8b1a-4fe7-aa5c-5aa8ac270b22',
    slug: 'mantiqueira-flores',
    name: 'Mantiqueira Flores Raras',
    document: '38.992.114/0001-44',
    is_active: true,
    created_at: '2025-02-15T14:30:00Z',
  },
];

export const INITIAL_TENANT_SETTINGS: Record<string, TenantSettings> = {
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11': {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    logo_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=200&q=80',
    logo_dark_url: '',
    favicon_url: '',
    primary_color: '#1C2D27',
    secondary_color: '#283618',
    accent_color: '#BC6C25',
    background_color: '#FAF8F5',
    font_family: 'Plus Jakarta Sans',
    whatsapp_number: '+5511999999999',
    whatsapp_display: '(11) 99999-9999',
    instagram_handle: '@elan.atelier',
    business_hours: 'Colheita e Ateliê: 05:30 - 19:00',
    emergency_phone: '(11) 98888-7777',
    delivery_radius_text: 'Despacho Climatizado: Grande São Paulo em até 120min',
    atelierName: 'ÉLAN ATELIER BOTÂNICO',
  },
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Esculturas Monumentais', slug: 'esculturas-monumentais', display_order: 1, is_active: true },
  { id: 'cat-2', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Buquês de Coleção', slug: 'buques-de-colecao', display_order: 2, is_active: true },
  { id: 'cat-3', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Plantas Raras em Grés', slug: 'plantas-raras-em-gres', display_order: 3, is_active: true },
];

export const INITIAL_OCCASIONS: Occasion[] = [
  { id: 'occ-1', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Romance & Devoção', slug: 'romance', icon_name: 'Heart', is_featured: true },
  { id: 'occ-2', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Arquitetura Interior', slug: 'interior', icon_name: 'Home', is_featured: true },
  { id: 'occ-3', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Celebração & Brinde', slug: 'celebracao', icon_name: 'Sparkles', is_featured: true },
  { id: 'occ-4', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Simpatia & Solenidade', slug: 'simpatia', icon_name: 'Feather', is_featured: false },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    category_id: 'cat-1',
    name: 'TERRA & PÉTALA ESCULTÓRICO',
    slug: 'terra-petala-escultorico',
    description: 'Vaso cerâmico em grés mineral torneado à mão. Peônias Alba Nobre e Hortênsias Macrophylla combinadas a galhos de oliveira toscana (65cm de envergadura).',
    base_price: 460,
    promotional_price: null,
    stock_status: 'in_stock',
    images: [
      'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=1000&q=80',
    ],
    botanical_care: {
      light: 'indireta',
      water: 'a_cada_2_dias',
      pet_friendly: true,
      temperature_celsius: '16°C - 22°C',
      vase_life_days: '14 dias garantidos',
    },
    occasions: ['interior', 'celebracao'],
    is_featured: true,
    display_order: 1,
    created_at: '2025-03-01T08:00:00Z',
  },
  {
    id: 'prod-2',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    category_id: 'cat-2',
    name: 'POÉSIE SILVESTRE & RANÚNCULOS',
    slug: 'poesie-silvestre-ranunculos',
    description: 'Camadas em degradê com rosas inglesas safra matinal, ranúnculos pérola, astilbe e eucalipto cinerea com laço desfiado de seda botânica.',
    base_price: 290,
    promotional_price: null,
    stock_status: 'in_stock',
    images: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1000&q=80',
    ],
    botanical_care: {
      light: 'meia_sombra',
      water: 'diaria',
      pet_friendly: true,
      temperature_celsius: '18°C - 24°C',
      vase_life_days: '12 dias',
    },
    occasions: ['romance', 'celebracao'],
    is_featured: true,
    display_order: 2,
    created_at: '2025-03-05T09:30:00Z',
  },
  {
    id: 'prod-3',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    category_id: 'cat-2',
    name: 'VELUDO & BORGONHA PROFUNDO',
    slug: 'veludo-borgonha-profundo',
    description: 'Dálias vinho negro, rosas toffee cappuccino, sementes de papoula secas e folhagens escuras em papel plissado texturizado com fita carmim.',
    base_price: 340,
    promotional_price: null,
    stock_status: 'low_stock',
    images: [
      'https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=1000&q=80',
    ],
    botanical_care: {
      light: 'indireta',
      water: 'a_cada_2_dias',
      pet_friendly: false,
      temperature_celsius: '18°C - 22°C',
      vase_life_days: '14 dias',
    },
    occasions: ['celebracao', 'interior'],
    is_featured: false,
    display_order: 3,
    created_at: '2025-03-10T11:00:00Z',
  },
  {
    id: 'prod-4',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    category_id: 'cat-1',
    name: 'COMISSÃO BOTÂNICA PRIVADA',
    slug: 'comissao-botanica-privada',
    description: 'Diálogo direto por WhatsApp com nossa diretora botânica para criar um arranjo sob medida com flores raras do dia harmonizadas ao seu projeto arquitetônico.',
    base_price: 520,
    promotional_price: null,
    stock_status: 'in_stock',
    images: [
      'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=1000&q=80',
    ],
    botanical_care: {
      light: 'indireta',
      water: 'diaria',
      pet_friendly: true,
      temperature_celsius: '18°C - 24°C',
      vase_life_days: '14 - 18 dias',
    },
    occasions: ['interior'],
    is_featured: true,
    display_order: 4,
    created_at: '2025-03-12T14:00:00Z',
  },
];

export const INITIAL_ADDONS: Addon[] = [
  {
    id: 'addon-1',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Urna de Cerâmica Grés Mineral',
    description: 'Vaso cerâmico em grés mineral torneado à mão em alta temperatura com acabamento texturizado.',
    price: 180,
    image_url: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=400&q=80',
    category: 'vaso',
    is_active: true,
  },
  {
    id: 'addon-2',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Tesoura Japonesa de Poda em Latão',
    description: 'Aço carbono forjado com cabos em latão para cortes angulares precisos a 45°.',
    price: 140,
    image_url: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=400&q=80',
    category: 'ferramenta',
    is_active: true,
  },
  {
    id: 'addon-3',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Vinho Tinto Natural Orgânico',
    description: 'Garrafa de vinho biodinâmico de pequena tiragem da Serra da Mantiqueira.',
    price: 195,
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=400&q=80',
    category: 'vinho',
    is_active: true,
  },
  {
    id: 'addon-4',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Caixa de Trufas Artesanais de Cacau Cru',
    description: '8 bombons com infusão botânica de alfazema, cumaru e café arábica.',
    price: 88,
    image_url: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=400&q=80',
    category: 'chocolate',
    is_active: true,
  },
];

export const INITIAL_DELIVERY_ZONES: DeliveryZone[] = [
  { id: 'zone-1', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', neighborhood_name: 'Jardins / Cerqueira César', city: 'São Paulo', fee: 25, estimated_time: '60 - 90 min', is_active: true },
  { id: 'zone-2', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', neighborhood_name: 'Itaim Bibi / Vila Nova Conceição', city: 'São Paulo', fee: 30, estimated_time: '60 - 90 min', is_active: true },
  { id: 'zone-3', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', neighborhood_name: 'Pinheiros / Alto de Pinheiros', city: 'São Paulo', fee: 35, estimated_time: '90 - 120 min', is_active: true },
  { id: 'zone-4', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', neighborhood_name: 'Higienópolis / Pacaembu', city: 'São Paulo', fee: 30, estimated_time: '60 - 90 min', is_active: true },
  { id: 'zone-5', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', neighborhood_name: 'Morumbi / Panamby', city: 'São Paulo', fee: 45, estimated_time: '90 - 120 min', is_active: true },
];

export const INITIAL_DELIVERY_SHIFTS: DeliveryShift[] = [
  { id: 'shift-1', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Manhã (09:00 - 13:00)', start_time: '09:00', end_time: '13:00', cutoff_time: '07:30', max_orders: 12, is_active: true },
  { id: 'shift-2', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Tarde (13:00 - 17:00)', start_time: '13:00', end_time: '17:00', cutoff_time: '11:00', max_orders: 16, is_active: true },
  { id: 'shift-3', tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', name: 'Crepúsculo (17:00 - 20:00)', start_time: '17:00', end_time: '20:00', cutoff_time: '15:00', max_orders: 8, is_active: true },
];

export const INITIAL_SITE_CONTENT: SiteContent[] = [
  {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    section: 'hero',
    key: 'hero_title_line_1',
    value_text: 'ARQUITETURA VIVA',
  },
  {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    section: 'hero',
    key: 'hero_title_line_2',
    value_text: 'para ESPAÇOS',
  },
  {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    section: 'hero',
    key: 'hero_title_line_3',
    value_text: 'RAROS.',
  },
  {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    section: 'hero',
    key: 'hero_description',
    value_text: 'Transcendemos o arranjo tradicional. Moldamos volumes botânicos autênticos, proporções assimétricas e cerâmicas de grés torneadas sob encomenda com despacho climatizado direto pelo WhatsApp.',
  },
  {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    section: 'hero',
    key: 'route_badge',
    value_text: 'HOLAMBRA → ATELIER JARDINS → SUA RESIDÊNCIA',
  },
  {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    section: 'about',
    key: 'manifesto_quote',
    value_text: 'FLORES TRATADAS NÃO COMO ADORNO, MAS COMO ESTRUTURAS ESPACIAIS QUE RESPIRAM.',
  },
  {
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    section: 'about',
    key: 'manifesto_description',
    value_text: 'Trabalhamos exclusivamente com produtores de Holambra e da Serra da Mantiqueira que respeitam o ciclo lunar da seiva. Sem câmaras frias agressivas, sem espumas fenólicas não-biodegradáveis.',
  },
];

export const INITIAL_ORDERS: OrderLog[] = [
  {
    id: 'ord-101',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    customer_name: 'Beatriz Vasconcellos',
    customer_phone: '(11) 98765-4321',
    recipient_name: 'Juliana e Renato Prado',
    recipient_phone: '(11) 97654-3210',
    delivery_address: 'Rua Bela Cintra, 1920, Apto 141 - Consolação, São Paulo - SP',
    items_json: [
      {
        product_id: 'prod-1',
        product_name: 'TERRA & PÉTALA ESCULTÓRICO',
        quantity: 1,
        unit_price: 460,
        addons: [{ name: 'Vela Artesanal Cera de Abelha & Figo Silvestre', price: 95 }],
      },
    ],
    dedication_card_json: {
      recipient: 'Juliana e Renato',
      sender: 'Beatriz e Carlos',
      message: 'Para habitar o novo lar com serenidade, luz e solene beleza. Parabéns pela nova conquista!',
      calligraphy_font: 'script',
      wax_seal: 'forest',
    },
    delivery_date: '2025-03-24',
    delivery_shift: 'Tarde (13:00 - 17:00)',
    total_amount: 585,
    whatsapp_generated_message: 'Pedido #101 confirmado para entrega na Bela Cintra.',
    status: 'confirmado',
    created_at: '2025-03-24T09:15:00Z',
  },
  {
    id: 'ord-102',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    customer_name: 'Felipe Camargo',
    customer_phone: '(11) 99123-8888',
    recipient_name: 'Helena Montenegro',
    recipient_phone: '(11) 98877-2233',
    delivery_address: 'Av. Brigadeiro Luís Antônio, 3400 - Jardim Paulista, São Paulo - SP',
    items_json: [
      {
        product_id: 'prod-2',
        product_name: 'POÉSIE SILVESTRE & RANÚNCULOS',
        quantity: 1,
        unit_price: 290,
      },
    ],
    dedication_card_json: {
      recipient: 'Helena',
      sender: 'Felipe',
      message: 'Em cada detalhe, a celebração do seu sorriso. Te amo muito.',
      calligraphy_font: 'serif',
      wax_seal: 'terracotta',
    },
    delivery_date: '2025-03-24',
    delivery_shift: 'Manhã (09:00 - 13:00)',
    total_amount: 320,
    status: 'em_producao',
    created_at: '2025-03-24T10:00:00Z',
  },
  {
    id: 'ord-103',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    customer_name: 'Renata Albuquerque',
    customer_phone: '(11) 99882-3344',
    recipient_name: 'Dra. Marina Sampaio',
    recipient_phone: '(11) 99776-5544',
    delivery_address: 'Rua Peixoto Gomide, 840, Sala 82 - Jardins, São Paulo - SP',
    items_json: [
      {
        product_id: 'prod-3',
        product_name: 'VELUDO & BORGONHA PROFUNDO',
        quantity: 1,
        unit_price: 340,
        addons: [{ name: 'Caixa de Trufas Artesanais de Cacau Cru', price: 88 }],
      },
    ],
    dedication_card_json: {
      recipient: 'Dra. Marina',
      sender: 'Equipe Albuquerque',
      message: 'Com profunda gratidão pela sua dedicação e carinho inestimável.',
      calligraphy_font: 'serif',
      wax_seal: 'gold',
    },
    delivery_date: '2025-03-24',
    delivery_shift: 'Tarde (13:00 - 17:00)',
    total_amount: 458,
    status: 'saiu_para_entrega',
    created_at: '2025-03-24T10:30:00Z',
  },
  {
    id: 'ord-104',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    customer_name: 'Marcos Vinicius',
    customer_phone: '(11) 98111-2233',
    recipient_name: 'Clara Silveira',
    recipient_phone: '(11) 98222-3344',
    delivery_address: 'Rua Oscar Freire, 1100 - Cerqueira César, São Paulo - SP',
    items_json: [
      {
        product_id: 'prod-1',
        product_name: 'TERRA & PÉTALA ESCULTÓRICO',
        quantity: 1,
        unit_price: 460,
      },
    ],
    dedication_card_json: {
      recipient: 'Clara',
      sender: 'Marcos',
      message: 'Feliz aniversário! Que seu dia seja luminoso como esta composição.',
      calligraphy_font: 'script',
      wax_seal: 'forest',
    },
    delivery_date: '2025-03-23',
    delivery_shift: 'Manhã (09:00 - 13:00)',
    total_amount: 485,
    status: 'entregue',
    created_at: '2025-03-23T08:00:00Z',
  },
  {
    id: 'ord-105',
    tenant_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    customer_name: 'Guilherme Toledo',
    customer_phone: '(11) 97654-9988',
    recipient_name: 'Isabela Fontes',
    recipient_phone: '',
    delivery_address: 'Rua Haddock Lobo, 1421 - Jardins, São Paulo - SP',
    items_json: [
      {
        product_id: 'prod-4',
        product_name: 'COMISSÃO BOTÂNICA PRIVADA',
        quantity: 1,
        unit_price: 520,
      },
    ],
    dedication_card_json: {
      recipient: 'Isabela',
      sender: 'Guilherme',
      message: 'Para o nosso jantar de noivado. Sempre nós.',
      calligraphy_font: 'script',
      wax_seal: 'gold',
    },
    delivery_date: '2025-03-25',
    delivery_shift: 'Crepúsculo (17:00 - 20:00)',
    total_amount: 545,
    status: 'iniciado_whatsapp',
    created_at: '2025-03-24T12:00:00Z',
  },
];
